# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filebrowser < Formula
  desc "File Browser is a create-your-own-cloud-kind of software where you can install it on a server, direct it to a path and then access your files through a nice web interface"
  homepage "https://filebrowser.org"
  version "2.27.0-b66bbb8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nerahikada/filebrowser/releases/download/v2.27.0-b66bbb8/darwin-amd64-filebrowser.tar.gz"
      sha256 "c2f2017015f1680662c9f9ef1034fac45597bcb4a12d47cbc3a155d3f728b167"

      def install
        bin.install "filebrowser"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nerahikada/filebrowser/releases/download/v2.27.0-b66bbb8/darwin-arm64-filebrowser.tar.gz"
      sha256 "ef0e6def4de9e5b3b219cf8687d82ff259e4e1e9eb9cc338dc419dd2fc949db7"

      def install
        bin.install "filebrowser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Nerahikada/filebrowser/releases/download/v2.27.0-b66bbb8/linux-armv6-filebrowser.tar.gz"
      sha256 "7636c5f6b3be6c1df8e74987313d427b4ea2a7da4b4f9f06740082a98ddb18cc"

      def install
        bin.install "filebrowser"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nerahikada/filebrowser/releases/download/v2.27.0-b66bbb8/linux-arm64-filebrowser.tar.gz"
      sha256 "6132d3c348d920969146f3aeca291d1ee2c9674347df22e3add555db2b51fd0e"

      def install
        bin.install "filebrowser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Nerahikada/filebrowser/releases/download/v2.27.0-b66bbb8/linux-amd64-filebrowser.tar.gz"
      sha256 "c504eb156cb4eddd12181cf6eb3d66d187b36a89bff1e5af9fea8cdb7d3eee68"

      def install
        bin.install "filebrowser"
      end
    end
  end
end
